apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: webapp
  labels:
    app: nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: webapp
          image: 606802968668.dkr.ecr.af-south-1.amazonaws.com/prod-webapps:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://production-api.villagesquare.io/v2"
            - name: NEXTAUTH_SECRET
              value: "REPLACE_WITH_PRODUCTION_SECRET"
            - name: NEXTAUTH_URL
              value: "https://villagesquare.io"
            - name: GOOGLE_CLIENT_ID
              value: "REPLACE_WITH_PRODUCTION_GOOGLE_CLIENT_ID"
            - name: GOOGLE_CLIENT_SECRET
              value: "REPLACE_WITH_PRODUCTION_GOOGLE_CLIENT_SECRET"
            - name: FACEBOOK_CLIENT_ID
              value: "REPLACE_WITH_PRODUCTION_FACEBOOK_CLIENT_ID"
