apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-web-ingress
  namespace: default
  annotations:

    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    acme.cert-manager.io/http01-ingress-class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: www.villagesquare.io
      http:
        paths:
          # - path: /_next
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nextjs-service
          #       port:
          #         number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 80
    - host: villagesquare.io
      http:
        paths:
          # - path: /_next
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nextjs-service
          #       port:
          #         number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 80
